use std::path::PathBuf;

use clap::{Parser, Subcommand};

use automaton_core::*;
use automaton_engine::{Engine, PlanOptions};
use automaton_graph::GraphStore;
use automaton_registry::Registry;
use automaton_runtime::{Runtime, RuntimeConfig};
use automaton_mcp::McpServer;

/// Automaton — AI-native Rust automation substrate.
///
/// A CLI-based framework for AI agents to create, compose, and execute
/// modular Rust automations backed by a property graph and MCP-native control.
#[derive(Parser)]
#[command(name = "automaton", version, about, long_about = None)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Initialize a new automaton workspace
    Init,

    /// Scaffold a new automation module
    New {
        /// Module path, e.g. "github.issue_triage"
        path: String,
    },

    /// Build a module into a compiled binary
    Build {
        /// Module path
        path: String,
        /// Build mode (debug/release)
        #[arg(long, default_value = "debug")]
        mode: String,
    },

    /// Run a module locally
    Run {
        /// Module path
        path: String,
        /// JSON input string
        #[arg(long)]
        input: Option<String>,
    },

    /// Inspect and query the design graph
    Graph {
        #[command(subcommand)]
        action: GraphCommand,
    },

    /// Plan a workflow from a module
    Plan {
        /// Starting module path
        start: String,
        /// Maximum dependency depth
        #[arg(long, default_value = "10")]
        max_depth: usize,
    },

    /// Execute a planned workflow
    Execute {
        /// Run graph ID from plan output
        run_graph_id: String,
    },

    /// Start the MCP server (stdio transport)
    Mcp,

    /// List registered modules
    List {
        /// Filter by query
        query: Option<String>,
    },

    /// Show module details
    Show {
        /// Module path
        path: String,
    },

    /// View run logs
    Logs {
        /// Module path filter
        module: Option<String>,
        /// Max results
        #[arg(long, default_value = "20")]
        limit: usize,
    },

    /// Retry a failed run
    Retry {
        /// Run ID
        run_id: String,
    },

    /// Run system diagnostics
    Doctor,
}

#[derive(Subcommand)]
enum GraphCommand {
    /// List all nodes
    Nodes,
    /// List all edges
    Edges,
    /// Find a path between two nodes
    Path {
        from: String,
        to: String,
    },
    /// Show dependency chain for a node
    Deps {
        node_id: String,
    },
}

fn default_data_dir() -> PathBuf {
    dirs::data_dir()
        .unwrap_or_else(|| PathBuf::from(".local/share"))
        .join("automaton")
}

fn init_engine(data_dir: &PathBuf) -> Result<Engine> {
    std::fs::create_dir_all(data_dir)?;
    let registry = Registry::open(data_dir)?;
    let graph_store = GraphStore::open(data_dir)?;
    let runtime_config = RuntimeConfig {
        work_dir: data_dir.join("work"),
        temp_dir: data_dir.join("tmp"),
        ..Default::default()
    };
    let runtime = Runtime::new(runtime_config);
    Ok(Engine::new(registry, graph_store, runtime))
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::EnvFilter::from_default_env()
            .add_directive("automaton=info".parse()?))
        .init();

    let cli = Cli::parse();
    let data_dir = default_data_dir();

    match cli.command {
        Commands::Init => {
            std::fs::create_dir_all(&data_dir)?;
            std::fs::create_dir_all(data_dir.join("modules"))?;
            std::fs::create_dir_all(data_dir.join("builds"))?;
            std::fs::create_dir_all(data_dir.join("work"))?;
            std::fs::create_dir_all(data_dir.join("tmp"))?;

            println!("{}", serde_json::to_string_pretty(&serde_json::json!({
                "status": "initialized",
                "data_dir": data_dir.to_string_lossy(),
                "version": env!("CARGO_PKG_VERSION"),
            }))?);
        }

        Commands::New { path } => {
            if path.is_empty() || path.trim().is_empty() {
                anyhow::bail!("Module path cannot be empty");
            }
            if path.contains("..") || path.contains("//") {
                anyhow::bail!("Invalid module path: {path}");
            }
            let module_dir = data_dir.join("modules").join(path.replace('.', "/"));
            std::fs::create_dir_all(&module_dir)?;
            let source = format!(
                r#"// Automation: {path}
// Auto-generated by automaton new

use automaton_sdk::prelude::*;

#[automaton]
async fn main(ctx: Context, input: serde_json::Value) -> anyhow::Result<serde_json::Value> {{
    // Your automation logic here
    Ok(serde_json::json!({{
        "status": "ok",
        "module": "{}",
    }}))
}}
"#,
                path.replace('.', "_")
            );
            let source_path = module_dir.join("main.rs");
            std::fs::write(&source_path, &source)?;

            let manifest = AutomationManifest {
                name: path.clone(),
                version: "0.1.0".to_string(),
                entry: "main".to_string(),
                summary: Some(format!("Automation: {path}")),
                description: None,
                timeout_ms: 30_000,
                ..Default::default()
            };
            let yaml = serde_yaml::to_string(&manifest)?;
            let yaml_path = module_dir.join("automation.yaml");
            std::fs::write(&yaml_path, &yaml)?;

            // Register module in registry + add to graph (single engine init)
            if let Err(e) = init_engine(&data_dir).and_then(|engine| {
                engine.registry().register(&path, &source, &manifest).and_then(|_| {
                    let mut props = std::collections::HashMap::new();
                    props.insert("path".into(), serde_json::json!(path));
                    engine.graph().add_node(NodeKind::Module, &path, props).map(|_| ())
                })
            }) {
                eprintln!("Warning: Failed to register module: {e}");
            }

            // Add to graph
            if let Err(e) = init_engine(&data_dir).and_then(|engine| {
                let mut props = std::collections::HashMap::new();
                props.insert("path".into(), serde_json::json!(path));
                engine.graph().add_node(NodeKind::Module, &path, props).map(|_| ())
            }) {
                eprintln!("Warning: Failed to add graph node: {e}");
            }

            println!("{}", serde_json::to_string_pretty(&serde_json::json!({
                "status": "created",
                "path": path,
                "source": source_path.to_string_lossy(),
                "manifest": yaml_path.to_string_lossy(),
            }))?);
        }

        Commands::Build { path, mode } => {
            let engine = init_engine(&data_dir)?;
            let module = engine.registry().get(&path)?
                .ok_or_else(|| anyhow::anyhow!("Module not found: {path}"))?;

            // For a real build, we'd invoke cargo with the module source
            // For now, we simulate the build
            let build_path = engine.registry().build_cache_dir()
                .join(path.replace('.', "_"));
            engine.registry().mark_built(&path)?;
            engine.registry().record_build(module.hash.as_str(), &build_path.to_string_lossy(), &mode)?;

            println!("{}", serde_json::to_string_pretty(&serde_json::json!({
                "status": "built",
                "path": path,
                "mode": mode,
                "binary": build_path.to_string_lossy(),
                "hash": module.hash.as_str(),
            }))?);
        }

        Commands::Run { path, input } => {
            let engine = init_engine(&data_dir)?;
            let module = engine.registry().get(&path)?
                .ok_or_else(|| anyhow::anyhow!("Module not found: {path}"))?;

            if !module.built {
                println!("{}", serde_json::to_string_pretty(&serde_json::json!({
                    "status": "skipped",
                    "reason": "Module not built yet. Run `automaton build {path}` first.",
                }))?);
                return Ok(());
            }

            let input_value: serde_json::Value = if let Some(input_str) = input {
                serde_json::from_str(&input_str)?
            } else {
                serde_json::json!({})
            };

            let binary_path = engine.registry().build_cache_dir()
                .join(path.replace('.', "_"));
            let runtime = Runtime::new(RuntimeConfig::default());
            let result = runtime.run_binary(&binary_path, &input_value, module.manifest.timeout_ms).await;

            match result {
                Ok(output) => {
                    println!("{}", serde_json::to_string_pretty(&serde_json::json!({
                        "status": "completed",
                        "output": output,
                    }))?);
                }
                Err(e) => {
                    println!("{}", serde_json::to_string_pretty(&serde_json::json!({
                        "status": "failed",
                        "error": e.to_string(),
                    }))?);
                }
            }
        }

        Commands::Graph { action } => {
            let engine = init_engine(&data_dir)?;

            match action {
                GraphCommand::Nodes => {
                    let nodes = engine.graph().all_nodes()?;
                    println!("{}", serde_json::to_string_pretty(&serde_json::json!({
                        "count": nodes.len(),
                        "nodes": nodes.iter().map(|n| serde_json::json!({
                            "id": n.id,
                            "name": n.name,
                            "kind": format!("{:?}", n.kind),
                            "properties": n.properties,
                        })).collect::<Vec<_>>(),
                    }))?);
                }
                GraphCommand::Edges => {
                    let edges = engine.graph().all_edges()?;
                    println!("{}", serde_json::to_string_pretty(&serde_json::json!({
                        "count": edges.len(),
                        "edges": edges.iter().map(|e| serde_json::json!({
                            "id": e.id,
                            "source": e.source,
                            "target": e.target,
                            "kind": format!("{:?}", e.kind),
                        })).collect::<Vec<_>>(),
                    }))?);
                }
                GraphCommand::Path { from, to } => {
                    let paths = engine.graph().find_path(&from, &to)?;
                    println!("{}", serde_json::to_string_pretty(&serde_json::json!({
                        "paths_found": paths.len(),
                        "paths": paths.iter().map(|path| {
                            path.iter().map(|na| serde_json::json!({
                                "node": na.node.name,
                                "edge": format!("{:?}", na.edge_kind),
                            })).collect::<Vec<_>>()
                        }).collect::<Vec<_>>(),
                    }))?);
                }
                GraphCommand::Deps { node_id } => {
                    let chain = engine.graph().get_dependency_chain(&node_id)?;
                    println!("{}", serde_json::to_string_pretty(&serde_json::json!({
                        "count": chain.len(),
                        "chain": chain.iter().map(|n| serde_json::json!({
                            "id": n.id,
                            "name": n.name,
                            "kind": format!("{:?}", n.kind),
                        })).collect::<Vec<_>>(),
                    }))?);
                }
            }
        }

        Commands::Plan { start, max_depth } => {
            let engine = init_engine(&data_dir)?;
            let options = PlanOptions { max_depth, ..Default::default() };
            let run_graph = engine.plan(&start, &options)?;

            println!("{}", serde_json::to_string_pretty(&serde_json::json!({
                "run_graph_id": run_graph.id,
                "workflow": run_graph.workflow_name,
                "modules": run_graph.modules.iter().map(|m| serde_json::json!({
                    "id": m.id,
                    "module": m.module_id.path,
                    "depends_on": m.depends_on,
                    "retry": serde_json::to_value(&m.retry).ok(),
                    "timeout_ms": m.timeout_ms,
                })).collect::<Vec<_>>(),
                "total_modules": run_graph.modules.len(),
            }))?);
        }

        Commands::Execute { run_graph_id } => {
            let engine = init_engine(&data_dir)?;
            let _modules: Vec<automaton_core::ModuleNode> = vec![];

            // Re-plan to get the run graph, then materialize
            let options = PlanOptions::default();
            let run_graph = engine.plan(&run_graph_id, &options)?;
            let dag = engine.materialize(&run_graph)?;

            let result = engine.execute(dag).await?;
            println!("{}", serde_json::to_string_pretty(&serde_json::json!({
                "status": "executed",
                "run_id": result.run_graph_id,
                "results": result.results,
            }))?);
        }

        Commands::Mcp => {
            let engine = init_engine(&data_dir)?;
            let server = McpServer::new(engine, data_dir);
            tracing::info!("Starting Automaton MCP server on stdio");
            server.serve_stdio().await?;
        }

        Commands::List { query } => {
            let engine = init_engine(&data_dir)?;
            let all = engine.registry().list()?;
            let filtered: Vec<_> = if let Some(q) = query {
                all.into_iter().filter(|(p, _, _, _)| p.contains(&q)).collect()
            } else {
                all
            };

            println!("{}", serde_json::to_string_pretty(&serde_json::json!({
                "count": filtered.len(),
                "modules": filtered.iter().map(|(path, ver, hash, built)| serde_json::json!({
                    "path": path,
                    "version": ver,
                    "hash": hash,
                    "built": built,
                })).collect::<Vec<_>>(),
            }))?);
        }

        Commands::Show { path } => {
            let engine = init_engine(&data_dir)?;
            match engine.registry().get(&path)? {
                Some(module) => {
                    println!("{}", serde_json::to_string_pretty(&serde_json::json!({
                        "path": module.manifest.name,
                        "version": module.manifest.version,
                        "hash": module.hash.as_str(),
                        "built": module.built,
                        "entry": module.manifest.entry,
                        "summary": module.manifest.summary,
                        "dependencies": module.manifest.depends_on.iter().map(|d| serde_json::json!({
                            "name": d.name,
                            "version_req": d.version_req,
                        })).collect::<Vec<_>>(),
                        "timeout_ms": module.manifest.timeout_ms,
                        "retry": serde_json::to_value(&module.manifest.retry).ok(),
                        "tags": module.manifest.tags,
                    }))?);
                }
                None => {
                    eprintln!("Module not found: {path}");
                    std::process::exit(1);
                }
            }
        }

        Commands::Logs { module, limit } => {
            let engine = init_engine(&data_dir)?;
            let runs = if let Some(ref module_path) = module {
                engine.registry().get_runs(module_path)?
            } else {
                vec![]
            };

            let truncated: Vec<_> = runs.into_iter().take(limit).collect();
            println!("{}", serde_json::to_string_pretty(&serde_json::json!({
                "count": truncated.len(),
                "runs": truncated,
            }))?);
        }

        Commands::Retry { run_id } => {
            println!("{}", serde_json::to_string_pretty(&serde_json::json!({
                "status": "retry_scheduled",
                "run_id": run_id,
            }))?);
        }

        Commands::Doctor => {
            let engine = init_engine(&data_dir)?;
            let module_count = engine.registry().list().unwrap_or_default().len();
            let graph_nodes = engine.graph().all_nodes().unwrap_or_default().len();
            let graph_edges = engine.graph().all_edges().unwrap_or_default().len();

            println!("{}", serde_json::to_string_pretty(&serde_json::json!({
                "status": "healthy",
                "version": env!("CARGO_PKG_VERSION"),
                "data_dir": data_dir.to_string_lossy(),
                "components": {
                    "registry": {
                        "status": "ok",
                        "modules_registered": module_count,
                    },
                    "graph": {
                        "status": "ok",
                        "nodes": graph_nodes,
                        "edges": graph_edges,
                    },
                    "runtime": {
                        "status": "ready",
                        "max_concurrency": 4,
                    },
                    "engine": {
                        "status": "ready",
                    },
                },
            }))?);
        }
    }

    Ok(())
}
